
align_args: true
align_parameter: false
break_after_functioncall_lp: true
break_after_functiondef_lp: true
break_before_functioncall_rp: true
break_before_functiondef_rp: true
chop_down_kv_table: true
chop_down_parameter: true
chop_down_table: true
column_limit: 120
column_table_limit: 80
continuation_indent_width: 2
double_quote_to_single_quote: true
extra_sep_at_table_end: true
indent_width: 2
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
spaces_before_call: 1
table_sep: ','
use_tab: false
