local M = {}

M.icons = {
  kind = {
    Array = " ",
    Boolean = " ", -- ◩
    Class = " ", -- 󰠱 🝆
    Color = " ",
    Comment = " ",
    Component = " ",
    Fragment = " ",
    Conditional = " ",
    Constant = "󰭸 ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Error = "󰛉 ",
    Event = " ",
    Field = "󰓽 ",
    File = " ",
    Folder = " ",
    Function = " ", -- 󰡱
    Interface = " ", -- 
    Key = "󰷖 ", -- 󰌋
    Keyword = "󰷖 ",
    Method = " ",
    Module = "󰶮 ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = "󰎠 ",
    Object = "󰅩 ",
    Operator = " ",
    Package = " ", -- " ",
    Property = "󰓽 ",
    Reference = " ",
    Snippet = " ",
    String = "󱀍 ",
    Struct = " ",
    Text = "󰈍 ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
    Spell = "󰓆 ",
  },
  diagnostics = {
    { name = "Error", text = " ", severity = vim.diagnostic.severity.ERROR },
    { name = "Warn", text = " ", severity = vim.diagnostic.severity.WARN },
    { name = "Hint", text = " ", severity = vim.diagnostic.severity.HINT },
    { name = "Info", text = " ", severity = vim.diagnostic.severity.INFO },
  },
  ui = {
    Duck = "󰇥 ",
    Bug = " ",
    BugOutline = " ",
    Robot = "󱙺 ",
    Exit = "󰿅 ",
    Cancel = "󰜺 ",
    Pause = "󰏦 ",
    Play = "󰐍 ",
    ArrowBack = "󰌍 ",
    ArrowInto = "󰆹 ",
    ArrowOut = " ",
    ArrowOver = "󰆷 ",
    Repeat = "🗘 ",
    Skip = "󱧧 ",
    Run = "󰜎 ",
    CheckMark = "✔ ",
    X = "✘ ",
    Add = " ",
    Edit = " ",
    Delete = " ",
    Branch = " ",
    Expanded = "🞃 ",
    Collapsed = "🞂 ",
    Text = "󰦨 ", -- 󰦪
    Command = " ",
    Prompt = "❯ ", -- ❯ ❱ ⧽
    Select = "  ", -- ➜  ⮞    🡺  🡲
    Light = " ",
    Separator = "┊",
    FillTexture = "󰔌 ",
    FillSlash = "╱",
    FillDot = "·",
    Space = "␣",
    CaretDown = "⌄",
    CaretDoubleRight = "»",
    CaretDoubleLeft = "«",
    MarkerDot = "󰍎 ",
    MarkerX = "󰼊 ",
    MarkerQuestion = "󰼇 ",
    MarkerExclamation = "󰼅 ",
  },
}

M.exclude_filetypes = {
  "",
  "DiffviewFiles",
  "TelescopePrompt",
  "Outline",
  "ccc-ui",
  "checkhealth",
  "dap-repl",
  "dap-terminal",
  "dapui_console",
  "dapui_hover",
  "fugitive",
  "harpoon",
  "help",
  "lazy",
  "lspinfo",
  "man",
  "mason",
  "netrw",
  "octo",
  "qf",
  "tsplayground",
  "undotree",
}

return M
