# https://github.com/mpv-player/mpv/blob/master/etc/input.conf

# Toggle audio filters
F1 af set "" ; show-text "Reset Audio Filters"
F2 af toggle "lavfi=[pan=stereo|c0=FC+LFE+FL+BL+SL|c1=FC+LFE+FR+BR+SR,loudnorm=I=-14:LRA=1:TP=-1:linear=false:dual_mono=true]" # https://news.ycombinator.com/item?id=41280567
# F2 af toggle "lavfi=[loudnorm=I=-16:TP=-3:LRA=4]"
# F3 af toggle "lavfi=[dynaudnorm=g=5:f=250:r=0.9:p=0.5]"
F3 af toggle "lavfi=[dynaudnorm=f=75:g=25:n=0:p=0.58],volume=softclip=yes"
F4 af toggle "lavfi=[alimiter=10:1:1:5:8000]"
F5 af toggle "lavfi=[acompressor=10]"
F6 af toggle "lavfi=[volume=1.5,pan=stereo|FL<0.5*c2+0.707*c0+0.707*c4+0.5*c3|FR<0.5*c2+0.707*c1+0.707*c5+0.5*c3]" # downmix 5.1 - https://superuser.com/a/1410620
F7 af toggle "lavfi=[lowpass=c=LFE:f=120,volume=1.5,pan=stereo|FL=0.5*FC+0.3*FLC+0.3*FL+0.3*BL+0.3*SL+0.5*LFE|FR=0.5*FC+0.3*FRC+0.3*FR+0.3*BR+0.3*SR+0.5*LFE]" # downmix 7.1
