#!/usr/bin/env bash

usage() {
    printf "%s\n%s\n" "$1" "$(
        cat <<EOF

A script to backup or restore dconf settings.
Usage: dconf-backup <command>

Commands:
    b,  backup      Export dconf settings specified at the top of the script
    r,  restore     Restore the dconf settings that were previously exported

EOF
    )"
    exit 1
}

declare -a backup_settings=(
    "org/gnome/desktop/wm"
    "org/gnome/settings-daemon/plugins/media-keys"
    "org/gnome/shell/keybindings"
    "org/gnome/terminal"
)

DCONF_CONFIG_DIR="$HOME/.config/dconf"
mkdir -p "$DCONF_CONFIG_DIR"

sanitize_filename() {
    echo "$DCONF_CONFIG_DIR/$(echo "$1" | tr '/' '_').conf"
}

backup() {
    for i in "${backup_settings[@]}"; do
        dconf dump "/$i/" >"$(sanitize_filename "$i")"
    done
}

restore() {
    for i in "${backup_settings[@]}"; do
        backup_file="$(sanitize_filename "$i")"
        [ -f "$backup_file" ] && [ -r "$backup_file" ] &&
            dconf load "/$i/" <"$backup_file"
    done
}

main() {
    if [ -n "$1" ]; then
        case $1 in
            b | backup | d | dump)
                backup
                ;;
            r | restore | l | load)
                restore
                ;;
            *)
                usage "Unknown command passed: $1"
                ;;
        esac
    else
        usage
    fi
}

main "$@"
