# vim:ft=ruby

if OS.mac?
  brew 'noti'                          # utility to display notifications from scripts
  brew 'trash'                         # rm, but put in the trash rather than completely delete

  # Applications
  cask 'ghostty'                       # a better terminal emulator
  cask 'wezterm'                       # a better terminal emulator
  cask 'karabiner-elements'            # keyboard customizer
  cask 'nikitabobko/tap/aerospace'     # a tiling window manager
  cask 'caffeine'                      # keep desktop awake

  # Fonts
  cask 'font-iosevka-nerd-font'
elsif OS.linux?
  brew 'xclip'                         # access to clipboard (similar to pbcopy/pbpaste)
end

# Latest versions of some core utilities
brew 'coreutils'                       # GNU core utils
brew 'bash'                            # bash shell
brew 'zsh'                             # zsh shell
brew 'git'                             # git version control
brew 'grep'                            # grep utility
brew 'gnu-sed'                         # sed utility
brew 'vim'                             # vim text editor

# Other packages
brew 'bash-completion@2'               # completion for bash
brew 'bat'                             # better cat
brew 'btop'                            # a top alternative
brew 'cloc'                            # lines of code counter
brew 'dict'                            # dictionary server protocol
brew 'entr'                            # file watcher / command runner
brew 'eza'                             # ls alternative
brew 'fd'                              # find alternative
brew 'fzf'                             # Fuzzy file searcher, used in scripts and in vim
brew 'gh'                              # GitHub CLI
brew 'git-delta'                       # a better git diff
brew 'glow'                            # markdown viewer
brew 'gnupg'                           # GPG
brew 'highlight'                       # code syntax highlighting
brew 'jq'                              # work with JSON files in shell scripts
brew 'lua'                             # lua language
brew 'mise'                            # mise-en-place dev env tool
brew 'neovim'                          # A better vim
brew 'pinentry-mac'                    # GPG
brew 'python'                          # python (latest)
brew 'ripgrep'                         # very fast file searcher
brew 'rsync'                           # backup utility
brew 'task'                            # taskwarrior (todo list)
brew 'tmux'                            # terminal multiplexer
brew 'tree'                            # pretty-print directory contents
brew 'tree-sitter-cli'                 # treesitter cli (for neovim)
brew 'vifm'                            # cli file explorer
brew 'w3m'                             # cli web browser
brew 'wdiff'                           # word differences in text files
brew 'wget'                            # internet file retriever
brew 'wordnet'                         # dictionary utility
