gui:
  showBottomLine: false
  showIcons: true
  theme:
    activeBorderColor:
      - "#98971a"
      - bold
    inactiveBorderColor:
      - "#a89984"
    optionsTextColor:
      - "#458588"
    selectedLineBgColor:
      - bold
      - "#3c3836"
    selectedRangeBgColor:
      - bold
      - "#3c3836"
    cherryPickedCommitBgColor:
      - "#689d6a"
    cherryPickedCommitFgColor:
      - "#458588"
    unstagedChangesColor:
      - "#cc2418"
  branchColors:
    "master": "#689d6a"
    "main": "#689d6a"
    "docs": "#d79921"
    "gh-pages": "#d79921"
    "dev": "#b16286"
    "benelan": "#d65d0e"
  authorColors:
    "Ben Elan": "#d65d0e"
git:
  disableForcePushing: true
  paging:
    pager: delta -s --paging=never --true-color=never --no-gitconfig --syntax-theme=gruvbox-dark
reporting: "off"
os:
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: o {{filename}}
  openLinkCommand: o {{link}}
