# https://github.com/artempyanykh/marksman/blob/main/docs/configuration.md

[core]
markdown.file_extensions = ["markdown", "md", "mdx"]

[completion]
# The style of wiki links completion. Options are:
# * "file-stem" complete using file name without an extension
# * "file-path-stem" same as above but using file path
# * "title-slug" use the file's title
wiki.style = "file-path-stem"

