return {
  "nvim-telescope/telescope.nvim", -- fuzzy finding tool
  cmd = "Telescope",
  dependencies = {
    "nvim-lua/plenary.nvim",
    {
      "nvim-telescope/telescope-fzf-native.nvim", -- fzf syntax for telescope
      build = "make",
    },
    -- "ThePrimeagen/git-worktree.nvim", -- Git worktree helper for bare repos
    -- "ThePrimeagen/harpoon", -- file marks on steroids
  },
  keys = function()
    -- when a count N is given to a telescope mapping called through the following
    -- function, the search is started in the Nth parent directory
    local function telescope_cwd(picker, args)
      require("telescope.builtin")[picker](
        vim.tbl_extend(
          "error",
          args or {},
          { cwd = ("../"):rep(vim.v.count) .. "." }
        )
      )
    end
    return {
      { "<leader>f", "<cmd>Telescope<cr>", "Fuzzy Find" },
      { "<leader>fo", "<cmd>Telescope oldfiles<cr>", "Find Recent File" },
      { "<leader>fb", "<cmd>Telescope buffers<cr>", "Find Buffer" },
      { "<leader>fr", "<cmd>Telescope resume<cr>", "Resume Previous Fuzzying" },
      {
        "<leader>ff",
        function()
          telescope_cwd("find_files", { hidden = true })
        end,
        "Find File",
      },
      {
        "<leader>ft",
        function()
          telescope_cwd "live_grep"
        end,
        "Find Text",
      },
      -- LSP keymaps
      -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
      { "<leader>lr", "<cmd>Telescope lsp_references<cr>", "References" },
      { "<leader>lq", "<cmd>Telescope quickfix<cr>", "Telescope Quickfix" },
      {
        "<leader>lQ",
        "<cmd>Telescope quickfixhistory<cr>",
        "Telescope Quickfix History",
      },
      {
        "<leader>lt",
        "<cmd>Telescope lsp_type_definitions<cr>",
        "Workspace Diagnostics",
      },
      {
        "<leader>ld",
        "<cmd>Telescope diagnostics bufnr=0 theme=get_ivy<cr>",
        "Buffer Diagnostics",
      },
      {
        "<leader>lD",
        "<cmd>Telescope diagnostics<cr>",
        "Workspace Diagnostics",
      },
      {
        "<leader>ls",
        "<cmd>Telescope lsp_document_symbols<cr>",
        "Document Symbols",
      },
      {
        "<leader>lS",
        "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>",
        "Workspace Symbols",
      },
      -- Git keymaps
      -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - --
      {
        "<leader>fg",
        function()
          telescope_cwd "git_files"
        end,
        "Find Git Files",
      },
      {
        "<leader>gb",
        "<cmd>Telescope git_branches<cr>",
        { "n", "x" },
        "Checkout Branch",
      },
      {
        "<leader>gc",
        "<cmd>Telescope git_bcommits<cr>",
        { "n", "x" },
        "Checkout Buffer Commit",
      },
      {
        "<leader>gC",
        "<cmd>Telescope git_commits<cr>",
        { "n", "x" },
        "Checkout Commit",
      },
      {
        "<leader>gg",
        "<cmd>Telescope git_status<cr>",
        { "n", "x" },
        "Checkout Commit",
      },
    }
  end,
  opts = function()
    return {
      defaults = {
        prompt_prefix = " ❯  ", -- ❯ ❱ ⧽
        selection_caret = "  ", -- ➜  ⮞     🡺  🡲
        multi_icon = "✘  ", -- ✘  ✔
        entry_prefix = "   ",
        layout_config = { prompt_position = "top" },
        sorting_strategy = "ascending",
        cycle_layout_list = { "horizontal", "vertical", "bottom_pane" },
        set_env = { ["COLORTERM"] = "truecolor" },
        file_ignore_patterns = {
          -- dev directories
          "%.git/",
          "node_modules/",
          "dist/",
          "build/",
          -- home directories
          "%.cache/",
          "%.var/",
          "%.mozilla/",
          "%.pki/",
          "%.cert/",
          "%.gnupg/",
          "%.ssh/",
          "~/Music",
          "~/Videos",
          "~/Steam",
          "~/Pictures",
          -- media files
          "%.mp3",
          "%.mp4",
          "%.mkv",
          "%.m4a",
          "%.m4p",
          "%.png",
          "%.jpeg",
          "%.avi",
          "%.ico",
          -- packages
          "%.7z",
          "%.dmg%",
          "%.gz",
          "%.iso",
          "%.jar",
          "%.rar",
          "%.tar",
          "%.zip",
          -- autogenerated files
          -- "%.tmp", "%.orig", "%.lock", "%.bak",
          -- compiled
          -- "%.com", "%.class", "%.dll", "%.exe", "%.o", "%.so", "%.map", "%.min.js",
        },
        vimgrep_arguments = {
          "rg",
          "--color=never",
          "--no-heading",
          "--with-filename",
          "--line-number",
          "--column",
          "--smart-case",
          "--trim",
          "--hidden",
          "--glob=!.git/",
          "--glob=!node_modules/",
        },
        mappings = {
          i = {
            ["<C-c>"] = require("telescope.actions").close,
            ["<Down>"] = require("telescope.actions").cycle_history_next,
            ["<Up>"] = require("telescope.actions").cycle_history_prev,
            ["<M-j"] = require("telescope.actions").cycle_history_next,
            ["<M-k>"] = require("telescope.actions").cycle_history_prev,
            ["<C-j>"] = require("telescope.actions").move_selection_next,
            ["<C-k>"] = require("telescope.actions").move_selection_previous,
            ["<tab>"] = require("telescope.actions").toggle_selection
              + require("telescope.actions").move_selection_next,
            ["<s-tab>"] = require("telescope.actions").toggle_selection
              + require("telescope.actions").move_selection_previous,
            ["<esc>"] = require("telescope.actions").close,
            ["<M-p>"] = require("telescope.actions.layout").toggle_preview,
            ["<M-m>"] = require("telescope.actions.layout").toggle_mirror,
            ["<A-l>"] = require("telescope.actions.layout").cycle_layout_next,
            ["<A-h>"] = require("telescope.actions.layout").cycle_layout_prev,
            ["<C-q>"] = function(...)
              require("telescope.actions").smart_send_to_qflist(...)
              require("telescope.actions").open_qflist(...)
            end,
          },
          n = {
            ["<C-j>"] = require("telescope.actions").move_selection_next,
            ["<C-k>"] = require("telescope.actions").move_selection_previous,
            ["<C-q>"] = function(...)
              require("telescope.actions").smart_send_to_qflist(...)
              require("telescope.actions").open_qflist(...)
            end,
          },
        },
      },
      pickers = {
        live_grep = { only_sort_text = true },
        buffers = {
          initial_mode = "normal",
          mappings = {
            i = { ["<C-d>"] = require("telescope.actions").delete_buffer },
            n = { ["dd"] = require("telescope.actions").delete_buffer },
          },
        },
        find_files = {
          mappings = {
            n = {
              -- change directory in normal mode
              ["<leader>cd"] = function(prompt_bufnr)
                local selection =
                  require("telescope.actions").state.get_selected_entry()
                local dir = vim.fn.fnamemodify(selection.path, ":p:h")
                require("telescope.actions").close(prompt_bufnr)
                vim.cmd(string.format("silent cd %s", dir))
              end,
            },
          },
        },
      },
    }
  end,
  config = function(_, opts)
    require("telescope").setup(opts)
    require("telescope").load_extension "fzf"
  end,
}
