prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 60
  prsLimit: 20
  issuesLimit: 20
  view: issues
  layout:
    prs:
      grow: true
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  refetchIntervalMinutes: 300
keybindings:
  prs:
    # Alternatives to spawning a new wezterm tab:
    #   - kitty @ launch --cwd={{.RepoPath}} bash -c '
    #   - cd {{.RepoPath}} && bash -c '
    - key: D
      # Open the PR's diff in Neovim to review/edit
      command: >
        wezterm cli spawn --cwd {{.RepoPath}} -- bash -c '
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":DiffviewOpen master...{{.HeadRefName}}"'
    - key: O
      # Open the PR itself in NeoVim to review with Octo
      command: >
        wezterm cli spawn --cwd {{.RepoPath}} -- bash -c '
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":Octo pr edit {{.PrNumber}}"'
    - key: E
      # Edit all of the changed files in NeoVim
      command: >
        wezterm cli spawn --cwd {{.RepoPath}} -- bash -c '
        gh pr checkout {{.PrNumber}} && nvim $(
          git diff --name-only {{.HeadRefName}} "$(
            git merge-base "$(
              basename "$(
                git rev-parse --abbrev-ref origin/HEAD
              )"
            )" {{.HeadRefName}}
          )"
        )'
repoPaths:
  Esri/calcite-components: ~/dev/calcite/calcite-components
  # *: ~/dev/* # consider putting all repos in a single directory
pager:
  diff: "delta"
