prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Calcite Design System
    filters: is:open repo:Esri/calcite-design-system
defaults:
  preview:
    open: true
    width: 60
  prsLimit: 42
  issuesLimit: 42
  view: issues
  layout:
    prs:
      grow: true
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  refetchIntervalMinutes: 300
keybindings:
# Alternatives to opening in a new tmux window:
#   - wezterm cli spawn --cwd {{.RepoPath}} -- bash -c '
#   - kitty @ launch --cwd={{.RepoPath}} bash -c '
#   - cd {{.RepoPath}} && bash -c '
  prs:
    - key: D
      # Open the PR's diff in Neovim to review/edit
      command: >
        tmux new-window -c {{.RepoPath}} '
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":DiffviewOpen master...{{.HeadRefName}}"
        '
    - key: O
      # Open the PR itself in NeoVim to review with Octo
      command: >
        tmux new-window -c {{.RepoPath}} '
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":Octo pr edit {{.PrNumber}}"
        '
    - key: E
      # Edit all of the changed files in NeoVim
      command: >
        tmux new-window -c {{.RepoPath}} '
        gh pr checkout {{.PrNumber}} && nvim $(
          git diff --name-only {{.HeadRefName}} "$(
            git merge-base "$(
              basename "$(
                git rev-parse --abbrev-ref origin/HEAD
              )"
            )" {{.HeadRefName}}
          )"
        )
        '
  issues:
    - key: P
      command: gh issue pin {{.IssueNumber}} --repo {.RepoName}
    - key: O
      # Open the issue in NeoVim with Octo
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c ":Octo issue edit {{.IssueNumber}}"
        '
repoPaths:
  Esri/*: ~/dev/work/*
  ArcGIS/*: ~/dev/work/*
  benelan/arcgis-esm-samples: ~/dev/work/arcgis-esm-samples/
  benelan/build-sizes: ~/dev/work/build-sizes
  benelan/calcite-samples: ~/dev/work/calcite-samples
  benelan/milestone-action: ~/dev/work/milestone-action
