return {
  { "catppuccin/nvim", enabled = false },
  { "dstein64/vim-startuptime", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "lukas-reineke/headlines.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/conform.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
}
