local M = {}

M.icons = {
  kind = {
    Array = " ",
    Boolean = "◩ ",
    Class = " ", -- 🝆
    Color = " ",
    Comment = " ",
    Component = " ",
    Fragment = " ",
    Conditional = " ",
    Constant = "󰭷 ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Error = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ", -- 󰡱
    Interface = " ", --
    Key = "󰌋 ",
    Keyword = "󰌋 ",
    Method = " ",
    Module = "󰶮 ",
    Namespace = " ",
    Null = "∅ ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ", -- " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  diagnostics = {
    { name = "Error", text = " ", severity = vim.diagnostic.severity.ERROR },
    { name = "Warn", text = " ", severity = vim.diagnostic.severity.WARN },
    { name = "Hint", text = " ", severity = vim.diagnostic.severity.HINT },
    { name = "Info", text = " ", severity = vim.diagnostic.severity.INFO },
  },
  ui = {
    Pause = "󰏦 ",
    Play = "󰐍 ",
    Repeat = "🗘 ",
    ArrowBack = "🠔 ",
    ArrowInto = "↳ ",
    ArrowOut = " ",
    ArrowOver = "↷ ",
    X = "✘ ",
    Done = "✔ ",
    Add = " ",
    Edit = " ",
    Delete = " ",
    Branch = " ",
    Expanded = "🞃 ",
    Collapsed = "🞂 ",
    Command = " ",
    Prompt = "❯ ", -- ❯ ❱ ⧽
    Select = "  ", -- ➜  ⮞    🡺  🡲
    Light = " ",
    Separator = "┊",
    FillSlash = "╱",
    FillDot = "·",
    Space = "␣",
    CaretDown = "⌄",
    CaretDoubleRight = "»",
    CaretDoubleLeft = "«",
  },
}

M.exclude_filetypes = {
  "",
  "DiffviewFiles",
  "TelescopePrompt",
  "ccc-ui",
  "checkhealth",
  "dap-repl",
  "fugitive",
  "help",
  "lazy",
  "lspinfo",
  "man",
  "mason",
  "netrw",
  "octo",
  "qf",
  "tsplayground",
  "undotree",
}

return M
