local M = {}

M.exclude_buftypes = { "terminal", "nofile", "help", "prompt" }

M.exclude_filetypes = {
  "dap-repl",
  "DiffviewFiles",
  "DressingSelect",
  "NvimTree",
  "Outline",
  "TelescopePrompt",
  "Trouble",
  "alpha",
  "dirvish",
  "fugitive",
  "lir",
  "neogitstatus",
  "oct",
  "packer",
  "spectre_panel",
  "toggleterm",
}

M.icons = {
  kind = {
    Array = "   ",
    Boolean = "   ",
    Class = "   ",
    Color = "   ",
    Constant = "   ",
    Constructor = "   ",
    Enum = "   ",
    EnumMember = "   ",
    Event = "   ",
    Field = "   ",
    File = "   ",
    Folder = "   ",
    Function = "   ",
    Interface = "   ",
    Key = "   ",
    Keyword = "   ",
    Method = "   ",
    Module = "   ",
    Namespace = "   ",
    Null = " ﳠ  ",
    Number = "   ",
    Object = "   ",
    Operator = "   ",
    Package = "   ",
    Property = "   ",
    Reference = "   ",
    Snippet = "   ",
    String = "   ",
    Struct = "   ",
    Text = "   ",
    TypeParameter = "   ",
    Unit = "   ",
    Value = "   ",
    Variable = "   ",
  },
}
return M
